cache:
- '%APPDATA%\cabal'
- '%APPDATA%\ghc'

install:
- choco install ghc
- refreshenv
- set PATH=%PATH%;C:\ProgramData\chocolatey\lib\ghc\tools\ghc-8.0.2\bin

build_script:
- cabal update
- cabal install happy
- cabal install --enable-tests --enable-benchmarks --disable-documentation --only-dependencies

test_script:
- cabal test

branches:
  only:
  - master
