packages:
- '.'
extra-deps:
- QuickCheck-2.9.2
- call-stack-0.1.0
- cpphs-1.20.2
- groom-0.1.2
- hspec-2.3.2
- hspec-core-2.3.2
- hspec-discover-2.3.2
- hspec-expectations-0.8.2
- integer-simple-0.1.1.1
- primitive-0.6.1.0
- quickcheck-io-0.1.3
- vector-0.11.0.0
- vector-algorithms-0.7.0.1
- vector-binary-instances-0.2.3.3
- vector-th-unbox-0.2.1.6
resolver: lts-2.22
